/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core.hpp>
#include <opencv2/objdetect.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
/* Header for class com_niu_flvthumbnail_FlvUtil */

#ifndef _Included_com_niu_flvthumbnail_FlvUtil
#define _Included_com_niu_flvthumbnail_FlvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_niu_flvthumbnail_FlvUtil
 * Method:    getFlvImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_niu_flvthumbnail_FlvUtil_getFlvImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
